# Usage:
# - install Docker Compose, see https://docs.docker.com/compose/install
# - open a console and `cd` into the folder that contains this file
# - note how the file references many environment variables, either set
#   them in your system or edit this file adding the values here
# - run `docker-compose up`
# - open the browser at http://127.0.0.1:10443
#
# For more information see
# https://github.com/Azure/azure-iot-pcs-remote-monitoring-java

version: "3"

services:
  reverseproxy:
    image: azureiotpcs/remote-monitoring-nginx:latest
    ports:
      - "10443:443"
    depends_on:
      - webui
      - auth
      - iothubmanager
      - devicesimulation
      - telemetry
      - config
    volumes:
      - /app/certs:/app/certs:ro

  webui:
    image: azureiotpcs/pcs-remote-monitoring-webui:latest
    ports:
      - "443:443"
    depends_on:
      - auth
      - iothubmanager
      - devicesimulation
      - telemetry
      - config
    environment:
      - PCS_KEYVAULT_NAME
      - PCS_AAD_APPID
      - PCS_AAD_APPSECRET

  auth:
    # TODO Use Java container
    image: azureiotpcs/pcs-auth-dotnet
    ports:
      - "9001:9001"
    environment:
      - PCS_KEYVAULT_NAME
      - PCS_AAD_APPID
      - PCS_AAD_APPSECRET

  iothubmanager:
    image: azureiotpcs/iothub-manager-java
    depends_on:
      - storageadapter
    ports:
      - "9002:9002"
    environment:
      - PCS_KEYVAULT_NAME
      - PCS_AAD_APPID
      - PCS_AAD_APPSECRET

  devicesimulation:
    image: azureiotpcs/device-simulation-dotnet:latest
    depends_on:
      - storageadapter
    ports:
      - "9003:9003"
    environment:
      - PCS_KEYVAULT_NAME
      - PCS_AAD_APPID
      - PCS_AAD_APPSECRET
    # This could be used to mount custom device models into the simulation
    #volumes:
    #  - ./sample-volume:/app/data:ro

  telemetry:
    image: azureiotpcs/telemetry-java:latest
    depends_on:
      - storageadapter
    ports:
      - "9004:9004"
    environment:
      - PCS_KEYVAULT_NAME
      - PCS_AAD_APPID
      - PCS_AAD_APPSECRET

  config:
    image: azureiotpcs/pcs-config-java:latest
    depends_on:
      - storageadapter
      - devicesimulation
      - telemetry
    ports:
      - "9005:9005"
    environment:
      - PCS_KEYVAULT_NAME
      - PCS_AAD_APPID
      - PCS_AAD_APPSECRET

  storageadapter:
    image: azureiotpcs/pcs-storage-adapter-java:latest
    ports:
      - "9022:9022"
    environment:
      - PCS_KEYVAULT_NAME
      - PCS_AAD_APPID
      - PCS_AAD_APPSECRET

  telemetryagent:
    image: azureiotpcs/telemetry-agent-java:latest
    depends_on:
      - telemetry
      - iothubmanager
    ports:
      - "9023:9023"
    environment:
      - PCS_KEYVAULT_NAME
      - PCS_AAD_APPID
      - PCS_AAD_APPSECRET
